export const ErrorCodes = {
  ACCESS_REQUIRED: "ACCESS_REQUIRED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  BAD_JSON: "BAD_JSON",
  CONFLICT: "CONFLICT",
  DEVICE_PENDING: "DEVICE_PENDING",
  DEVICE_REVOKED: "DEVICE_REVOKED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  NOT_FOUND: "NOT_FOUND"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
